/* Generated from power_policy/protocol/power_policy_v1.json. Do not edit. */
#ifndef DENZIC_POWER_POLICY_V1_GENERATED_H
#define DENZIC_POWER_POLICY_V1_GENERATED_H

#include <stdint.h>

#define DENZIC_POWER_POLICY_V1_CONTRACT_NAME "denzic_power_policy_v1"
#define DENZIC_POWER_POLICY_V1_CONTRACT_VERSION (1u)

typedef enum {
    DENZIC_POWER_POLICY_V1_BLOCKER_RECORDING = 0,
    DENZIC_POWER_POLICY_V1_BLOCKER_AUDIO_TRANSPORT = 1,
    DENZIC_POWER_POLICY_V1_BLOCKER_DIAGNOSTIC = 2,
    DENZIC_POWER_POLICY_V1_BLOCKER_PAIRING = 3,
    DENZIC_POWER_POLICY_V1_BLOCKER_RECONNECT = 4,
    DENZIC_POWER_POLICY_V1_BLOCKER_STORAGE = 5,
    DENZIC_POWER_POLICY_V1_BLOCKER_COMMAND = 6,
    DENZIC_POWER_POLICY_V1_BLOCKER_EXTERNAL_POWER = 7,
    DENZIC_POWER_POLICY_V1_BLOCKER_OTA = 8,
    DENZIC_POWER_POLICY_V1_BLOCKER_TOUCH = 9,
    DENZIC_POWER_POLICY_V1_BLOCKER_MENU = 10,
    DENZIC_POWER_POLICY_V1_BLOCKER_DISPLAY = 11,
    DENZIC_POWER_POLICY_V1_BLOCKER_BOOT = 12,
} denzic_power_policy_v1_blocker_t;

typedef enum {
    DENZIC_POWER_POLICY_V1_STATE_ACTIVE = 0,
    DENZIC_POWER_POLICY_V1_STATE_CONNECTED_IDLE = 1,
    DENZIC_POWER_POLICY_V1_STATE_DISCONNECTED_IDLE = 2,
    DENZIC_POWER_POLICY_V1_STATE_SHUTDOWN_REQUESTED = 3,
} denzic_power_policy_v1_state_t;

typedef enum {
    DENZIC_POWER_POLICY_V1_SHUTDOWN_REASON_NONE = 0,
    DENZIC_POWER_POLICY_V1_SHUTDOWN_REASON_LONG_IDLE = 1,
    DENZIC_POWER_POLICY_V1_SHUTDOWN_REASON_MANUAL = 2,
    DENZIC_POWER_POLICY_V1_SHUTDOWN_REASON_LOW_BATTERY = 3,
} denzic_power_policy_v1_shutdown_reason_t;

#define DENZIC_POWER_POLICY_V1_MAX_BLOCKER_INDEX (31u)

#endif
