/* Generated from battery/protocol/battery_v1.json. Do not edit. */
#ifndef DENZIC_BATTERY_V1_GENERATED_H
#define DENZIC_BATTERY_V1_GENERATED_H

#include <stdint.h>

#define DENZIC_BATTERY_V1_CONTRACT_NAME "denzic_battery_v1"
#define DENZIC_BATTERY_V1_CONTRACT_VERSION (1u)

typedef enum {
    DENZIC_BATTERY_V1_CHARGE_STATE_UNKNOWN = 0,
    DENZIC_BATTERY_V1_CHARGE_STATE_DISCHARGING = 1,
    DENZIC_BATTERY_V1_CHARGE_STATE_CHARGING = 2,
    DENZIC_BATTERY_V1_CHARGE_STATE_FULL = 3,
} denzic_battery_v1_charge_state_t;

typedef enum {
    DENZIC_BATTERY_V1_NOTIFY_REASON_NONE = 0,
    DENZIC_BATTERY_V1_NOTIFY_REASON_INITIAL = 1,
    DENZIC_BATTERY_V1_NOTIFY_REASON_LEVEL_DELTA = 2,
    DENZIC_BATTERY_V1_NOTIFY_REASON_PERIODIC = 3,
    DENZIC_BATTERY_V1_NOTIFY_REASON_FORCED = 4,
} denzic_battery_v1_notify_reason_t;

#define DENZIC_BATTERY_V1_BATTERY_SERVICE_UUID16 (6159u)
#define DENZIC_BATTERY_V1_BATTERY_LEVEL_UUID16 (10777u)
#define DENZIC_BATTERY_V1_INVALID_LEVEL (255u)
#define DENZIC_BATTERY_V1_DEFAULT_EMPTY_MV (2850u)
#define DENZIC_BATTERY_V1_DEFAULT_FULL_MV (4150u)
#define DENZIC_BATTERY_V1_NOTIFY_THRESHOLD_PERCENT (1u)
#define DENZIC_BATTERY_V1_FORCE_REFRESH_INTERVAL_MS (60000u)
#define DENZIC_BATTERY_V1_CHARGE_FULL_MIN_MV (4050u)
#define DENZIC_BATTERY_V1_CHARGE_FULL_MIN_PERCENT (88u)
#define DENZIC_BATTERY_V1_CHARGE_FULL_DEBOUNCE_MS (10000u)

#endif
