/* Generated from host_audio/protocol/host_audio_v1.json. Do not edit. */
#ifndef DENZIC_HOST_AUDIO_V1_GENERATED_H
#define DENZIC_HOST_AUDIO_V1_GENERATED_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DENZIC_HOST_AUDIO_V1_CONTRACT_NAME "denzic_host_audio_v1"
#define DENZIC_HOST_AUDIO_V1_CONTRACT_VERSION (1u)
#define DENZIC_HOST_AUDIO_V1_PCM_SAMPLE_RATE_HZ (16000u)
#define DENZIC_HOST_AUDIO_V1_PCM_CHANNELS (1u)
#define DENZIC_HOST_AUDIO_V1_PCM_SAMPLE_WIDTH_BITS (16u)
#define DENZIC_HOST_AUDIO_V1_PCM_BLOCK_ALIGN (DENZIC_HOST_AUDIO_V1_PCM_CHANNELS * (DENZIC_HOST_AUDIO_V1_PCM_SAMPLE_WIDTH_BITS / 8u))
#define DENZIC_HOST_AUDIO_V1_PCM_BYTE_RATE (DENZIC_HOST_AUDIO_V1_PCM_SAMPLE_RATE_HZ * DENZIC_HOST_AUDIO_V1_PCM_BLOCK_ALIGN)
#define DENZIC_HOST_AUDIO_V1_WAV_HEADER_BYTES (44u)
#define DENZIC_HOST_AUDIO_V1_WAV_FMT_CHUNK_BYTES (16u)
#define DENZIC_HOST_AUDIO_V1_WAV_AUDIO_FORMAT_PCM (1u)
#define DENZIC_HOST_AUDIO_V1_ASR_OPENAI_TRANSCRIPTION_ENDPOINT "https://api.openai.com/v1/audio/transcriptions"
#define DENZIC_HOST_AUDIO_V1_ASR_DEFAULT_MODEL "gpt-4o-transcribe"
#define DENZIC_HOST_AUDIO_V1_ASR_DEFAULT_MAX_UPLOAD_BYTES (26214400ull)
#define DENZIC_HOST_AUDIO_V1_ASR_REQUEST_TIMEOUT_SECONDS (120u)

#ifdef __cplusplus
}
#endif

#endif
