/* Generated from ota/protocol/ota_v1.json. Do not edit. */
#ifndef DENZIC_OTA_V1_GENERATED_H
#define DENZIC_OTA_V1_GENERATED_H

#define DENZIC_OTA_V1_PROTOCOL_NAME "denzic_ota_v1"
#define DENZIC_OTA_V1_MAGIC "DOV1"
#define DENZIC_OTA_V1_PROTOCOL_VERSION (1u)
#define DENZIC_OTA_V1_CONTROL_BYTES (16u)
#define DENZIC_OTA_V1_DATA_HEADER_BYTES (4u)
#define DENZIC_OTA_V1_STATUS_BYTES (24u)
#define DENZIC_OTA_V1_STATUS_FLAG_ACTIVE_LINK_CONFIRMED (1u)
#define DENZIC_OTA_V1_OP_BEGIN (1u)
#define DENZIC_OTA_V1_OP_SYNC (2u)
#define DENZIC_OTA_V1_OP_FINISH (3u)
#define DENZIC_OTA_V1_OP_ABORT (4u)
#define DENZIC_OTA_V1_STATE_IDLE (0u)
#define DENZIC_OTA_V1_STATE_ERASING (1u)
#define DENZIC_OTA_V1_STATE_RECEIVING (2u)
#define DENZIC_OTA_V1_STATE_COMPLETE (3u)
#define DENZIC_OTA_V1_STATE_ERROR (4u)
#define DENZIC_OTA_V1_ERROR_NONE (0u)
#define DENZIC_OTA_V1_ERROR_BAD_MAGIC (1u)
#define DENZIC_OTA_V1_ERROR_BAD_STATE (2u)
#define DENZIC_OTA_V1_ERROR_BAD_SIZE (3u)
#define DENZIC_OTA_V1_ERROR_OFFSET_MISMATCH (4u)
#define DENZIC_OTA_V1_ERROR_STORAGE_WRITE (5u)
#define DENZIC_OTA_V1_ERROR_STORAGE_BEGIN (6u)
#define DENZIC_OTA_V1_ERROR_STORAGE_FINISH (7u)

#endif
