/* Generated from device_health/protocol/device_health_v1.json. Do not edit. */
#ifndef DENZIC_DEVICE_HEALTH_V1_GENERATED_H
#define DENZIC_DEVICE_HEALTH_V1_GENERATED_H

#include <stdint.h>

#define DENZIC_DEVICE_HEALTH_V1_CONTRACT_NAME "denzic_device_health_v1"
#define DENZIC_DEVICE_HEALTH_V1_CONTRACT_VERSION (1u)

typedef enum {
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_UNKNOWN = 0,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_POWER_ON = 1,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_EXTERNAL = 2,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_SOFTWARE = 3,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_PANIC = 4,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_WATCHDOG = 5,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_DEEP_SLEEP = 6,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_BROWNOUT = 7,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_USB = 8,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_JTAG = 9,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_POWER_GLITCH = 10,
    DENZIC_DEVICE_HEALTH_V1_RESET_REASON_CPU_LOCKUP = 11,
} denzic_device_health_v1_reset_reason_t;

typedef enum {
    DENZIC_DEVICE_HEALTH_V1_CHECK_STATE_PASSED = 0,
    DENZIC_DEVICE_HEALTH_V1_CHECK_STATE_FAILED = 1,
    DENZIC_DEVICE_HEALTH_V1_CHECK_STATE_NOT_REQUIRED = 2,
    DENZIC_DEVICE_HEALTH_V1_CHECK_STATE_RECOVERED = 3,
} denzic_device_health_v1_check_state_t;

typedef enum {
    DENZIC_DEVICE_HEALTH_V1_RUNTIME_ALERT_NONE = 0,
    DENZIC_DEVICE_HEALTH_V1_RUNTIME_ALERT_HEAP_PRESSURE = 1,
    DENZIC_DEVICE_HEALTH_V1_RUNTIME_ALERT_LINK_CHURN = 2,
} denzic_device_health_v1_runtime_alert_t;

#define DENZIC_DEVICE_HEALTH_V1_SAFE_MODE_THRESHOLD (3u)

#endif
