/* Generated from voice_activation/protocol/voice_activation_v1.json. Do not edit. */
#ifndef DENZIC_VOICE_ACTIVATION_V1_GENERATED_H
#define DENZIC_VOICE_ACTIVATION_V1_GENERATED_H

#include <stdint.h>

#define DENZIC_VOICE_ACTIVATION_V1_CONTRACT_NAME "denzic_voice_activation_v1"
#define DENZIC_VOICE_ACTIVATION_V1_CONTRACT_VERSION (1u)

typedef enum {
    DENZIC_VOICE_ACTIVATION_V1_STATE_DISABLED = 0,
    DENZIC_VOICE_ACTIVATION_V1_STATE_MONITORING = 1,
    DENZIC_VOICE_ACTIVATION_V1_STATE_SPEECH_CONFIRMING = 2,
    DENZIC_VOICE_ACTIVATION_V1_STATE_RECORDING = 3,
    DENZIC_VOICE_ACTIVATION_V1_STATE_TAIL = 4,
    DENZIC_VOICE_ACTIVATION_V1_STATE_COOLDOWN = 5,
} denzic_voice_activation_v1_state_t;

typedef enum {
    DENZIC_VOICE_ACTIVATION_V1_ACTION_NONE = 0,
    DENZIC_VOICE_ACTIVATION_V1_ACTION_START = 1,
    DENZIC_VOICE_ACTIVATION_V1_ACTION_STOP = 2,
} denzic_voice_activation_v1_action_t;

typedef enum {
    DENZIC_VOICE_ACTIVATION_V1_STOP_REASON_NONE = 0,
    DENZIC_VOICE_ACTIVATION_V1_STOP_REASON_SILENCE = 1,
    DENZIC_VOICE_ACTIVATION_V1_STOP_REASON_MAX_DURATION = 2,
} denzic_voice_activation_v1_stop_reason_t;

typedef enum {
    DENZIC_VOICE_ACTIVATION_V1_PHRASE_SIGNAL_NONE = 0,
    DENZIC_VOICE_ACTIVATION_V1_PHRASE_SIGNAL_KEYWORD_MODEL = 1,
    DENZIC_VOICE_ACTIVATION_V1_PHRASE_SIGNAL_LOCAL_TRANSCRIPT = 2,
} denzic_voice_activation_v1_phrase_signal_t;

typedef enum {
    DENZIC_VOICE_ACTIVATION_V1_GATE_DECISION_PENDING = 0,
    DENZIC_VOICE_ACTIVATION_V1_GATE_DECISION_ACCEPT = 1,
    DENZIC_VOICE_ACTIVATION_V1_GATE_DECISION_REJECT = 2,
} denzic_voice_activation_v1_gate_decision_t;

#define DENZIC_VOICE_ACTIVATION_V1_DEFAULT_SPEECH_CONFIRM_MS (300u)
#define DENZIC_VOICE_ACTIVATION_V1_DEFAULT_PRE_ROLL_MS (600u)
#define DENZIC_VOICE_ACTIVATION_V1_DEFAULT_SILENCE_STOP_MS (1000u)
#define DENZIC_VOICE_ACTIVATION_V1_DEFAULT_TAIL_MS (250u)
#define DENZIC_VOICE_ACTIVATION_V1_DEFAULT_MIN_SESSION_MS (500u)
#define DENZIC_VOICE_ACTIVATION_V1_DEFAULT_MAX_SESSION_MS (60000u)
#define DENZIC_VOICE_ACTIVATION_V1_DEFAULT_COOLDOWN_MS (1500u)
#define DENZIC_VOICE_ACTIVATION_V1_DEFAULT_LOCAL_CONFIRMATION_START_MS (1800u)

#endif
