/* Generated from ble_windows/protocol/ble_windows_v1.json. Do not edit. */
#ifndef DENZIC_BLE_WINDOWS_V1_GENERATED_H
#define DENZIC_BLE_WINDOWS_V1_GENERATED_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DENZIC_BLE_WINDOWS_V1_CONTRACT_NAME "denzic_ble_windows_v1"
#define DENZIC_BLE_WINDOWS_V1_CONTRACT_VERSION (1u)

#define DENZIC_BLE_WINDOWS_V1_DEFAULT_DISCOVERY_TIMEOUT_MS (15000u)
#define DENZIC_BLE_WINDOWS_V1_OPTIONAL_READ_TIMEOUT_MS (2000u)
#define DENZIC_BLE_WINDOWS_V1_CCCD_ENABLE_TIMEOUT_MS (8000u)
#define DENZIC_BLE_WINDOWS_V1_ASYNC_POLL_INTERVAL_MS (1u)
#define DENZIC_BLE_WINDOWS_V1_CREATE_NO_WINDOW_FLAG (134217728u)
#define DENZIC_BLE_WINDOWS_V1_CCCD_ENABLE_RETRY_DELAYS_COUNT (3u)

typedef enum {
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_DEVICE_MISSING = 0,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_DEVICE_ASLEEP = 1,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_MISSING_PAIRING = 2,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_LOW_POWER_IDLE_DISCONNECT = 3,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_PAIRED_BUT_DISCONNECTED = 4,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_STALE_GATT_SERVICE = 5,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_CCCD_PROTOCOL_ERROR = 6,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_MISSING_DIS_FIRMWARE_REVISION = 7,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_BACKGROUND_CONTENTION = 8,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_OTA_REBOOT_WINDOW = 9,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_WINDOWS_BLUETOOTH_SERVICE_RESET_NEEDED = 10,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_ACCESS_DENIED = 11,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_UNSUPPORTED_PLATFORM = 12,
    DENZIC_BLE_WINDOWS_V1_FAILURE_KIND_UNKNOWN = 13,
} denzic_ble_windows_v1_failure_kind_t;

static const uint32_t denzic_ble_windows_v1_cccd_enable_retry_delays_ms
[DENZIC_BLE_WINDOWS_V1_CCCD_ENABLE_RETRY_DELAYS_COUNT] = {250u, 750u, 1500u};

#ifdef __cplusplus
}
#endif

#endif
