/* Generated from speaker_verification/protocol/speaker_verification_v1.json. Do not edit. */
#ifndef DENZIC_SPEAKER_VERIFICATION_V1_GENERATED_H
#define DENZIC_SPEAKER_VERIFICATION_V1_GENERATED_H

#include <stdint.h>

#define DENZIC_SPEAKER_VERIFICATION_V1_CONTRACT_NAME "denzic_speaker_verification_v1"
#define DENZIC_SPEAKER_VERIFICATION_V1_CONTRACT_VERSION (1u)

typedef enum {
    DENZIC_SPEAKER_VERIFICATION_V1_CANDIDATE_ORIGIN_MANUAL = 0,
    DENZIC_SPEAKER_VERIFICATION_V1_CANDIDATE_ORIGIN_AUTOMATIC = 1,
    DENZIC_SPEAKER_VERIFICATION_V1_CANDIDATE_ORIGIN_ENROLLMENT = 2,
} denzic_speaker_verification_v1_candidate_origin_t;

typedef enum {
    DENZIC_SPEAKER_VERIFICATION_V1_STATE_IDLE = 0,
    DENZIC_SPEAKER_VERIFICATION_V1_STATE_BUFFERING = 1,
    DENZIC_SPEAKER_VERIFICATION_V1_STATE_RELEASED = 2,
    DENZIC_SPEAKER_VERIFICATION_V1_STATE_DISCARDED = 3,
    DENZIC_SPEAKER_VERIFICATION_V1_STATE_ERROR = 4,
} denzic_speaker_verification_v1_state_t;

typedef enum {
    DENZIC_SPEAKER_VERIFICATION_V1_VERDICT_PENDING = 0,
    DENZIC_SPEAKER_VERIFICATION_V1_VERDICT_MATCH = 1,
    DENZIC_SPEAKER_VERIFICATION_V1_VERDICT_NON_MATCH = 2,
    DENZIC_SPEAKER_VERIFICATION_V1_VERDICT_UNAVAILABLE = 3,
} denzic_speaker_verification_v1_verdict_t;

typedef enum {
    DENZIC_SPEAKER_VERIFICATION_V1_ACTION_NONE = 0,
    DENZIC_SPEAKER_VERIFICATION_V1_ACTION_BUFFER = 1,
    DENZIC_SPEAKER_VERIFICATION_V1_ACTION_RELEASE = 2,
    DENZIC_SPEAKER_VERIFICATION_V1_ACTION_DISCARD = 3,
    DENZIC_SPEAKER_VERIFICATION_V1_ACTION_BYPASS = 4,
} denzic_speaker_verification_v1_action_t;

#define DENZIC_SPEAKER_VERIFICATION_V1_DEFAULT_SCORE_MILLI (500u)
#define DENZIC_SPEAKER_VERIFICATION_V1_DEFAULT_MIN_CANDIDATE_MS (1000u)
#define DENZIC_SPEAKER_VERIFICATION_V1_DEFAULT_MAX_CANDIDATE_MS (10000u)

#endif
