/* Generated from device_control/protocol/device_control_v1.json. Do not edit. */
#ifndef DENZIC_DEVICE_CONTROL_V1_GENERATED_H
#define DENZIC_DEVICE_CONTROL_V1_GENERATED_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DENZIC_DEVICE_CONTROL_V1_CONTRACT_NAME "denzic_device_control_v1"
#define DENZIC_DEVICE_CONTROL_V1_CONTRACT_VERSION (1u)

typedef enum {
    DENZIC_DEVICE_CONTROL_V1_TRANSPORT_UNKNOWN = 0,
    DENZIC_DEVICE_CONTROL_V1_TRANSPORT_BLE = 1,
    DENZIC_DEVICE_CONTROL_V1_TRANSPORT_USB = 2,
    DENZIC_DEVICE_CONTROL_V1_TRANSPORT_WIFI = 3,
    DENZIC_DEVICE_CONTROL_V1_TRANSPORT_SERIAL = 4,
    DENZIC_DEVICE_CONTROL_V1_TRANSPORT_OTHER = 255,
} denzic_device_control_v1_transport_t;

typedef enum {
    DENZIC_DEVICE_CONTROL_V1_LIFECYCLE_STATE_UNKNOWN = 0,
    DENZIC_DEVICE_CONTROL_V1_LIFECYCLE_STATE_DISCONNECTED = 1,
    DENZIC_DEVICE_CONTROL_V1_LIFECYCLE_STATE_DISCOVERING = 2,
    DENZIC_DEVICE_CONTROL_V1_LIFECYCLE_STATE_CONNECTING = 3,
    DENZIC_DEVICE_CONTROL_V1_LIFECYCLE_STATE_SECURING = 4,
    DENZIC_DEVICE_CONTROL_V1_LIFECYCLE_STATE_READY = 5,
    DENZIC_DEVICE_CONTROL_V1_LIFECYCLE_STATE_RECOVERING = 6,
    DENZIC_DEVICE_CONTROL_V1_LIFECYCLE_STATE_OWNED_ELSEWHERE = 7,
    DENZIC_DEVICE_CONTROL_V1_LIFECYCLE_STATE_FAILED = 8,
} denzic_device_control_v1_lifecycle_state_t;

typedef enum {
    DENZIC_DEVICE_CONTROL_V1_OWNERSHIP_STATE_UNKNOWN = 0,
    DENZIC_DEVICE_CONTROL_V1_OWNERSHIP_STATE_UNPAIRED = 1,
    DENZIC_DEVICE_CONTROL_V1_OWNERSHIP_STATE_LOCAL = 2,
    DENZIC_DEVICE_CONTROL_V1_OWNERSHIP_STATE_MANUAL_UNPAIRED = 3,
    DENZIC_DEVICE_CONTROL_V1_OWNERSHIP_STATE_EXTERNAL = 4,
} denzic_device_control_v1_ownership_state_t;

typedef enum {
    DENZIC_DEVICE_CONTROL_V1_OPERATION_KIND_UNKNOWN = 0,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_KIND_DISCOVER = 1,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_KIND_CONNECT = 2,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_KIND_SECURE = 3,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_KIND_READ_CAPABILITIES = 4,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_KIND_READ_SETTING = 5,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_KIND_WRITE_SETTING = 6,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_KIND_INVOKE_COMMAND = 7,
} denzic_device_control_v1_operation_kind_t;

typedef enum {
    DENZIC_DEVICE_CONTROL_V1_OPERATION_RESULT_ACCEPTED = 1,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_RESULT_SUCCEEDED = 2,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_RESULT_REJECTED = 3,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_RESULT_CANCELLED = 4,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_RESULT_TIMED_OUT = 5,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_RESULT_TRANSPORT_LOST = 6,
    DENZIC_DEVICE_CONTROL_V1_OPERATION_RESULT_FAILED = 7,
} denzic_device_control_v1_operation_result_t;

typedef enum {
    DENZIC_DEVICE_CONTROL_V1_ERROR_CATEGORY_NONE = 0,
    DENZIC_DEVICE_CONTROL_V1_ERROR_CATEGORY_DEVICE = 1,
    DENZIC_DEVICE_CONTROL_V1_ERROR_CATEGORY_TRANSPORT = 2,
    DENZIC_DEVICE_CONTROL_V1_ERROR_CATEGORY_SECURITY = 3,
    DENZIC_DEVICE_CONTROL_V1_ERROR_CATEGORY_HOST = 4,
    DENZIC_DEVICE_CONTROL_V1_ERROR_CATEGORY_PROTOCOL = 5,
    DENZIC_DEVICE_CONTROL_V1_ERROR_CATEGORY_OWNERSHIP = 6,
    DENZIC_DEVICE_CONTROL_V1_ERROR_CATEGORY_UNSUPPORTED = 7,
    DENZIC_DEVICE_CONTROL_V1_ERROR_CATEGORY_TIMEOUT = 8,
    DENZIC_DEVICE_CONTROL_V1_ERROR_CATEGORY_RESOURCE = 9,
} denzic_device_control_v1_error_category_t;

#ifdef __cplusplus
}
#endif

#endif
